# Generated by Django 4.2.7 on 2025-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_minutos',
            field=models.IntegerField(default=120),
        ),
    ]
